__BRYTHON__.version_info = [2, '0.rc2', '20140117-221208', 'alpha', 0]
__BRYTHON__.builtin_module_names = ["posix","builtins",
    "crypto_js",
    "hashlib",
    "javascript",
    "json",
    "marshal",
    "math",
    "re",
    "time",
    "_ajax",
    "_browser",
    "_html",
    "_io",
    "_os",
    "_svg",
    "_sys",
    "_timer",
    "_websocket",
    "__random",
    ]
