__BRYTHON__.implementation = [2, 0, 0, 'rc', 2]
__BRYTHON__.version_info = [3, 3, 0, 'alpha', 0]
__BRYTHON__.builtin_module_names = ["posix","builtins",
    "crypto_js",
    "hashlib",
    "javascript",
    "json",
    "marshal",
    "math",
    "time",
    "_ajax",
    "_browser",
    "_html",
    "_io",
    "_jsre",
    "_jsre",
    "_os",
    "_svg",
    "_sys",
    "_timer",
    "_websocket",
    "__random",
    ]
