__BRYTHON__.version_info = [1, 3, '20131207-094336', 'alpha', 0]
__BRYTHON__.builtin_module_names = ["posix","builtins",
    "crypto_js",
    "hashlib",
    "javascript",
    "json",
    "math",
    "random",
    "re",
    "time",
    "_ajax",
    "_browser",
    "_html",
    "_os",
    "_svg",
    "_timer",
    "_websocket"]
